In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
#need open anaconda-jupyter prior to excution
import numpy as np
x=np.array([1,2,3,4]).reshape(2,2)
y=np.array([2,1,1,1]).reshape(2,2)
alph0=1
beta0=2

def compute_posterior(X, y, alph, beta):
    #### **** YOUR CODE HERE **** ####
    Mu=np.linalg.inv(X.T@X+alph/beta*np.identity((X.T@X).shape[0]))@X.T@y
    SIGMA=1/beta*np.linalg.inv(X.T@X+alph/beta*np.identity((X.T@X).shape[0]))

    return Mu, SIGMA
def VI(X_train, y_train):
    #### **** YOUR CODE HERE **** ####
    a0,b0,c0,d0=10**(-4),10**(-4),10**(-4),10**(-4)
    an,cn=a0+X_train.shape[1]/2,c0+X_train.shape[0]/2
    alph0,beta0=a0/b0,c0/d0
    mu_n,sig_n=compute_posterior(X_train, y_train, alph0, beta0)
    i=0
    while i<len(X_train):
        bn=b0+(mu_n.T@mu_n+np.trace(sig_n))/2
        dn=d0+(y_train-X_train@mu_n).T@(y_train-X_train@mu_n)/2
        alphn,betan=an/bn,cn/dn
        mu_n,sig_n=compute_posterior(X_train, y_train, alphn, betan)
        i+=1

    return an,bn,cn,dn, mu_n, sig_n

VI(x,y)

(1.0001,
 array([[0.52287946, 0.39765872],
        [0.39765872, 0.33710512]]),
 1.0001,
 array([[0.7079973 , 0.24011343],
        [0.24011343, 0.08150086]]),
 array([[-0.31902232, -0.08966345],
        [ 0.61587077,  0.35843157]]),
 array([[ 0.42363254, -0.09936965],
        [-0.09936965,  0.02735405]]))